# Generated by Django 5.2.3 on 2025-06-24 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Cadastro Aprovado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=350, verbose_name='Título do Curso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do Curso')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='cursos/capas/', verbose_name='Imagem de Capa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('instrutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Instrutor')),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=350, verbose_name='Título da Aula')),
                ('descricao', models.TextField(verbose_name='Descrição da Aula')),
                ('link_video', models.URLField(verbose_name='Link do Vídeo')),
                ('material_apoio', models.FileField(blank=True, null=True, upload_to='cursos/materiais/', verbose_name='Material de Apoio')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
