# Generated by Django 5.2.3 on 2025-06-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='link_video',
        ),
        migrations.AddField(
            model_name='aula',
            name='youtube_video_id',
            field=models.CharField(default='', help_text='Cole aqui apenas o código do vídeo, não a URL completa. Ex: dQw4w9WgXcQ', max_length=100, verbose_name='ID do vídeo no Youtube'),
            preserve_default=False,
        ),
    ]
