# Generated by Django 5.2.3 on 2025-06-28 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_pergunta_resposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='votos',
            field=models.ManyToManyField(blank=True, related_name='respostas_votadas', to=settings.AUTH_USER_MODEL, verbose_name='Votos'),
        ),
    ]
