# Generated by Django 5.2.3 on 2025-06-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_resposta_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='aulas_concluidas',
            field=models.ManyToManyField(blank=True, related_name='concluida_por', to='cursos.aula'),
        ),
    ]
