# Generated by Django 5.2.3 on 2025-06-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_associado_aulas_concluidas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Este campo é preenchido automaticamente.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='cursos.categoria'),
        ),
    ]
