# Generated by Django 5.2.3 on 2025-07-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome da Organização')),
                ('dono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organização_dono', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='associado',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associados', to='cursos.organizacao'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='cursos.organizacao'),
        ),
        migrations.AddField(
            model_name='curso',
            name='organizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.organizacao'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('organizacao', 'nome')},
        ),
    ]
