# Generated by Django 5.2.3 on 2025-07-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_organizacao_associado_organizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='associados', to='cursos.organizacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='cursos.organizacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.organizacao'),
            preserve_default=False,
        ),
    ]
