# Generated by Django 5.2.3 on 2025-07-14 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_associado_organizacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicoDiscussao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=355, verbose_name='Títullo do Tópico')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos_criados', to=settings.AUTH_USER_MODEL)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos_discussao', to='cursos.organizacao')),
            ],
            options={
                'verbose_name': 'Tópico de Discussão',
                'verbose_name_plural': 'Tópicos de Discussão',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Comentário')),
                ('arquivo_anexo', models.FileField(blank=True, null=True, upload_to='forum/anexos/', verbose_name='Anexar Ficheiro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_feitos', to=settings.AUTH_USER_MODEL)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='cursos.topicodiscussao')),
            ],
            options={
                'verbose_name': 'Comentário do Tópico',
                'verbose_name_plural': 'Comentários de Tópicos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
