# Generated by Django 5.2.3 on 2025-07-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_topicodiscussao_comentariotopico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariotopico',
            options={'ordering': ['data_criacao'], 'verbose_name': 'Comentário do Tópico', 'verbose_name_plural': 'Comentários de Tópicos'},
        ),
        migrations.AddField(
            model_name='associado',
            name='cursos_inscritos',
            field=models.ManyToManyField(blank=True, related_name='inscritos', to='cursos.curso'),
        ),
    ]
