# Generated by Django 5.2.3 on 2025-07-18 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_alter_comentariotopico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='pergunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.pergunta'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='resposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.resposta'),
        ),
    ]
