# Generated by Django 5.2.3 on 2025-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_notificacao_pergunta_alter_notificacao_resposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='associado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
    ]
