# Generated by Django 5.2.3 on 2025-07-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_associado_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=600, verbose_name='Texto da Opção')),
                ('correta', models.BooleanField(default=False, verbose_name='É a resposta correta?')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='cursos.perguntaquiz')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Quiz')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='cursos.curso')),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='perguntaquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='cursos.quiz'),
        ),
        migrations.CreateModel(
            name='ResultadoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField()),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_quiz', to='cursos.associado')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.quiz')),
            ],
        ),
    ]
