# Generated by Django 5.2.3 on 2025-08-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_perguntaquiz_opcaoresposta_quiz_perguntaquiz_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_tentativas',
            field=models.PositiveIntegerField(default=3, verbose_name='Máximo de Tentativas'),
        ),
        migrations.AddField(
            model_name='resultadoquiz',
            name='tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
