# Generated by Django 5.2.3 on 2025-09-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_quiz_max_tentativas_resultadoquiz_tentativas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilInstrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='instrutores/fotos/', verbose_name='Foto de Perfil')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia do Instrutor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_instrutor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
